# Coral Recovery Prediction Configuration

# Data Configuration
data:
  data_path: "data/"
  target_column: "status"
  test_size: 0.2
  random_state: 42
  
  # Primary data file for training
  primary_file: "bleaching.csv"

# Model Configurations
models:
  xgboost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.08
    subsample: 0.8
    colsample_bytree: 0.8
    colsample_bylevel: 0.8
    reg_alpha: 0.05
    reg_lambda: 0.5
    min_child_weight: 5
    gamma: 0.05
    random_state: 42
    objective: "binary:logistic"
    eval_metric: "logloss"
    scale_pos_weight: 4.5  # Handle class imbalance
    
  neural_network:
    hidden_layers: [256, 128, 64, 32]
    dropout_rate: 0.4
    learning_rate: 0.0005
    epochs: 150
    batch_size: 64
    validation_split: 0.25
    early_stopping_patience: 15
    random_state: 42
    class_weight: {0: 0.55, 1: 2.45}  # Handle class imbalance
    
  ensemble:
    weights: [0.6, 0.4]  # XGBoost weight, Neural Network weight

# Analysis Configuration
analysis:
  cv_folds: 3
  feature_importance_top_n: 15
  save_plots: true
  output_dir: "results/"
  
  # Cross-validation settings
  cv_random_state: 42
  cv_shuffle: true
  cv_stratify: true
  
  # Feature selection
  feature_selection:
    method: "mutual_info"  # mutual_info, rfe, tree_based
    k_best: 50
    
  # Preprocessing
  preprocessing:
    handle_missing: "median"  # median, mean, drop
    scale_features: true
    encode_categorical: "label"  # onehot, label
    resampling: null  # smote, adasyn, smoteenn, undersample, null
    threshold_optimization: true  # Optimize classification threshold
    
# Output Configuration
output:
  save_models: true
  save_predictions: true
  save_feature_importance: true
  save_evaluation_metrics: true
  plot_formats: ["png", "pdf"]
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "results/coral_prediction.log"
  console_output: true

# Random Seeds for Reproducibility
random_seeds:
  global_seed: 42
  numpy_seed: 42
  tensorflow_seed: 42
  sklearn_seed: 42